Ponder.registry((event) => {
	event.create(['umapyoi:jewel'])
		.scene("kubejs:cygames", "如何游玩赛马娘热血喧闹大感谢祭", "kubejs:dead_soul_kick_the_floor", (scene, utils) => {
          scene.showBasePlate()
          scene.idle(20)
          scene.text(90, "“赛马娘热血喧闹大感谢祭”是一款由Cygames和Arc System Works合作开发的一款派对游戏，这款游戏是以世界倒数第一IP“赛马娘 Pretty Derby”为原型所开发的游戏")
        })
})
/*
scene.configureBasePlate(0, 0, 3)
            scene.showBasePlate()
            scene.idle(20)
            scene.world.setBlocks([1, 4, 1], 'kubejs:high_altitude_objects_spinning_infinitely_with_bass_kick_can_turn_some_things_into_helicopter_dust_machine')
            scene.world.showSection([1, 4, 1], Direction.DOWN)
            scene.idle(3)
            scene.world.setBlocks([1, 3, 1], 'minecraft:bedrock')
            scene.world.showSection([1, 3, 1], Direction.UP)
            scene.idle(5)
            scene.text(40, "这个机器需要在高于256格的高空中运行，并且运行中将会直接替换掉下方的方块（即使是基岩）", [1.5, 4.5, 1.5])
            scene.idle(45)
            scene.addKeyframe()
            scene.text(30, "向机器里面输入2片棕色神秘花瓣和2片黄色神秘花瓣……")
            scene.showControls(20, [1.5, 4.5, 1.5], "left")
                 .withItem('botania:yellow_petal') 
            scene.showControls(20, [1.5, 4.5, 1.5], "right")
                 .withItem('botania:brown_petal')
            scene.idle(40)
            scene.text(85, "等待一小会")
            scene.idle(80)
            scene.addKeyframe()
            scene.idle(20)
            scene.text(30, "就会在机器的底部输出一个科比吉斯！")
            scene.world.setBlocks([1, 3, 1], 'endless_modpack_ingredients:kobejs', false)
            scene.idle(40)
            scene.text(30, "科比吉斯是一种可掉落的方块……", [1.5, 3.5, 1.5])
            scene.idle(40)
            scene.world.setBlocks([1, 3, 1], 'air', false)
            scene.world.setBlocks([1, 1, 1], 'endless_modpack_ingredients:kobejs', false)
            scene.world.showSection([1, 1, 1], Direction.DOWN)
            scene.text(30, "就像这样，它掉到了地板上")
            scene.idle(40)
            scene.addKeyframe()
            scene.text(30, "接下来挖开这个产物……", [1.5, 1.5, 1.5])
            scene.showControls(30, [2, 1, 2], "DOWN")
                 .leftClick()
                 .withItem('mekanism:atomic_disassembler')
            scene.idle(40)
            scene.world.setBlocks([1, 1, 1], 'air')
            scene.world.createItemEntity([1, 1, 1], Direction.DOWN, '4x kubejs:he_li_c_o_pt_er_dust')
            scene.text(50, "就会出现四个耐摔合金粉了！")
*/